[tool.poetry]
name = "trakt-scrobbler"
version = "1.3.0-beta.1"
description = "Scrobbler for trakt.tv that supports VLC, Plex, MPC-HC, and MPV"
authors = ["iamkroot <kroot.patel@gmail.com>"]
readme = "README.md"
repository = "https://github.com/iamkroot/trakt-scrobbler"
license = "GPL-2.0-only"
keywords = ["trakt", "scrobbler"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.22.0"
guessit = "^3.1.0"
appdirs = "^1.4.3"
pywin32 = {version = "^227", platform = "win32"}
win10toast = {version = "^0.9", platform = "win32"}
cleo = "^0.7.6"
confuse = "^1.3.0"
pysocks = {version = "^1.7.1", optional = true}
jeepney = {version = "^0.6", platform = "linux"}

[[tool.poetry.dependencies.urlmatch]]
# for some reason, poetry picks the MacOS package by default
url = "https://files.pythonhosted.org/packages/84/4e/654a4b6b335b339da7208ca1e54a34d1180e94c09b11b63dd76ee731b378/urlmatch-1.0.1.tar.gz"
markers = "sys_platform != 'darwin'"

[[tool.poetry.dependencies.urlmatch]]
version = "^1.0.1"
markers = "sys_platform == 'darwin'"

[tool.poetry.dev-dependencies]

[tool.poetry.extras]
socks = ["pysocks"]

[tool.poetry.scripts]
trakts = "trakt_scrobbler.console:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.pyright]
reportGeneralTypeIssues = false
